### ISSUE TITLE
CommandError('Bad input buffer (not an ARCommand)')

### ISSUE THREAD

**Issue by RnoB** [N-Bz/bybop#12]
Hi,
I am having issue with the last firmware 4.4.0 and a Bebop2. The following command raises error which did not appear under the firmware 4.0.5

drone = Bybop_Device.create_and_connect(device, d2c_port, controller_type, controller_name)

Exception in thread Thread-1:
Traceback (most recent call last):
  File "../src/Bybop_Commands.py", line 212, in unpack_command
    (i_proj, i_cls, i_cmd) = struct.unpack('<BBH', buf[:4])
struct.error: unpack requires a bytes object of length 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "../src/Bybop_NetworkAL.py", line 112, in _read_loop
    self._listener.data_received(type, buf, seq, recv_data)
  File "../src/Bybop_Network.py", line 179, in data_received
    self._process_data(buf, seq, recv_data)
  File "../src/Bybop_Network.py", line 185, in _process_data
    self._listener.data_received(buf, recv_data)
  File "../src/Bybop_Device.py", line 248, in data_received
    dico, ok = unpack_command(data)
  File "../src/Bybop_Commands.py", line 214, in unpack_command
    raise CommandError('Bad input buffer (not an ARCommand)')
Bybop_Commands.CommandError: 'Bad input buffer (not an ARCommand)'

We were getting similar problems with this program
https://github.com/Cubillosxy/MYO-PYTHON-BEBOP/tree/master/core
Strangely the drone still seem to register some commands but not always reliably. Do you know why would the new firmware creates those errors?
Best

**Comment by N-Bz** [comment]
This issue should be corrected on the master branch.
